---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  # - botkube
  - grafana
  - kube-system
  # - kube-prometheus-stack
  # - loki
  # - dashboard
  # - influxdb
  # - karma
  # - thanos
  # - speedtest-exporter
  # - cronitor-heartbeat
  # - node-problem-detector
  # - vector
